services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
      POSTGRES_DB: invoice_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:4.14.0
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
      LOCALSTACK_HOST: localhost
      SQS_ENDPOINT_STRATEGY: path
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "awslocal", "sqs", "list-queues"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 5s

  mailpit:
    image: axllent/mailpit:v1.30.3
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 5s

volumes:
  postgres_data:
